#!/usr/bin/env python
from peyotl.api import APIWrapper
from peyotl import pretty_dict_str
e = APIWrapper().studies.properties()
d = {}
for k, v in e.items():
    l = list(v)
    l.sort()
    d[k] = l
print(pretty_dict_str(d))
